version: '3.8'

version: "3"
services:
  api:
    container_name: api
    build: ./api # Localisation du Dockerfile dans notre cas dans le dossier racine
    ports:
      - 8800:8800 # Nous exposons le port 8800
    volumes:
      - ./:/usr/src/app/api # Le volume du WORKDIR
      - /usr/src/app/node_modules
    environment:
      - PORT=8800 # Nous pouvons définir ici plusieurs variables d'environnement
    depends_on:
      - mongo
  mongo:
    image: mongo:3.6
    volumes:
      - mongo-storage:/data/db # Nous pouvons ajouter un volume à ce container afin de stocker les données de la base
    expose:
      - 27017
    ports:
      - 27017:27017

# Définition des volumes:
volumes:
  mongo-storage:
    driver: local